// Generated by https://quicktype.io

export interface PokemonLista {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
    id:   number;
    img:  string;
}
